version: "3.9"
services:
  user-service:
    image: user-service
    working_dir: /user-service
    container_name: user-service
    build:
      context: ./packages/user-service
      dockerfile: development.Dockerfile
    ports:
      - 3000:3000
    networks:
      - microservices
  mongodb:
    image: mongo
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: some 64 byte username string. 1234 ain't enough.
      MONGO_INITDB_ROOT_PASSWORD: a_very_strong_password_indeed. lorem ipsum dolor sit amet.
    ports:
      - 27017:27017
    command:
      - "--logpath"
      - "/var/log/mongodb/mongod.log"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices
volumes:
  mongodb_data:
networks:
  microservices:
    driver: bridge
